### DISCUSSION TITLE
how to add an image in a template header?

### DISCUSSION THREAD

**Discussion by Abdelkrim** [david-lev/pywa#102] [Q&A]
# use case

1. I would like to send a template containing an image in its header.

![image](https://github.com/user-attachments/assets/376ef668-124d-4ca3-a373-8f003e6d0ea2)

2. It works when I use postman - see below

# Question

how can I reproduce the postman body by using PyWa

# PyWa-based source code

``` python
@wa.on_message(pywa.filters.matches("start", ignore_case=True))
def start(client: pywa.WhatsApp, msg: pywa.types.Message):
    logging.info("Received start message")
    wa.send_template(
        to=os.getenv("PHONE_NUMBER_TO_SEND_TO"),
        template=pywa.types.Template(
            name="my_template_name",
            language=pywa.types.Template.Language.FRENCH,
            header=pywa.types.Image(id="1234567890")),
        ),
    )
``` 

# whatsapp endpoint 

`https://graph.facebook.com/{{Version}}/{{Phone-Number-ID}}/messages`

# body of postman 
```yaml
{
    "messaging_product": "whatsapp",
    "recipient_type": "individual",
    "to": "{{Recipient-Phone-Number}}",
    "type": "template",
    "template": {
        "name": "my_template_name",
        "language": {
            "code": "FR"
        },
        "components": [
            {
                "type": "header",
                "parameters": [
                    {
                        "type": "image",
                        "image": {
                            "id": "1234567890"
                        }
                    }
                ]
            }
        ]
    }
}
```
